import './game.css';

export default function Leaderboard()
{
    
    return(
        <div className='back'>
        <div className='table1'>
            <table className='table1'>
            <tr>
            <th>Name</th>
            <th>Score (You/Computer)</th>
            <th>Result</th>
            <th>Time</th>
            </tr>
             <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr>
            <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr>
            <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr>
            <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr>
            <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr>
            <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr>
            <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr>
            <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr> <tr>
            <td>Juan</td>
            <td>5/4</td>
            <td>Win</td>
            <td>5:00</td>
            </tr>
            <tr>
            <td>Pedro</td>
            <td>3/4</td>
            <td>Lose</td>
            <td>6:30</td>
            </tr>
            </table>
        </div>
        </div>
    );
}